<?php 
$servername = "localhost";
$username = "trackeraccess";
$password = "finntestsql";
$dbname = "clashtracker";

$apiKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImE3ZTcwYTNkLWViNGEtNDMxNy1hMTRjLWVmMjMyZjM1YjU2NSIsImlhdCI6MTcxNjIzNTE4MCwic3ViIjoiZGV2ZWxvcGVyL2I0NWU5YTJiLTc1OGEtZWZmNi0xNWE2LTcyNmI4MzhlNDk3YyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjYyLjE0My4xNjIuMTMzIl0sInR5cGUiOiJjbGllbnQifV19.gaIUWme1vyrGCd1hMyp52mdbag9jJikQmKod1PoO5dHBNO0h7b3-IR9rnBwubnp2mS-_n36v-hnERBFw-NsVBA";
?>